name: deploy st thomas b & b app

on:
  push:
    branches:
      - main

jobs:
  setup_and_tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      SST_STAGE: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::643476110649:role/github-ci-role
          aws-region: us-east-1

      # Setup pnpm and cache dependencies
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Types
        run: npx sst types

      - name: Compile
        run: |
          for d in packages/*/ ; do
            pushd "$d"
            pnpm typecheck
            popd
          done

      - name: Run tests
        run: pnpm test:run

  deploy_prod:
    needs: setup_and_tests
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env:
      SST_STAGE: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::643476110649:role/github-ci-role
          aws-region: us-east-1

      - name: Deploy
        run: pnpm run deploy
