name: deploy st thomas b & b app

on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env:
      SST_STAGE: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::643476110649:role/github-ci-role
            aws-region: us-east-1

      - uses: pnpm/action-setup@v3
        name: Setup pnpm
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]
        
      - name: Types
        run: npx sst types
              
      - name: Compile
        run: |
          for d in packages/*/ ; do
            pushd "$d"
            pnpm typecheck
            popd
          done

      # - name: Run tests
      #   run: pnpm test:run

      - name: Deploy
        run: pnpm run deploy
